/**
 * Created by alexanderbol on 09/01/2016.
 */
export const SET_EDIT_MODE = 'SET_EDIT_MODE';
export const SET_LEARN_MODE = 'SET_LEARN_MODE';
export const SET_SORTED_BY = 'SET_SORTED_BY';
export const FETCH_LOCALE_SUCCEED = 'FETCH_LOCALE_SUCCEED';
export const FETCH_LANGUAGES_SUCCEED = 'FETCH_LANGUAGES_SUCCEED';
export const FETCH_DICTIONARIES_REQUEST_SUCCEED = 'FETCH_DICTIONARIES_REQUEST_SUCCEED';
export const AJAX_REQUEST_STARTED = 'AJAX_REQUEST_STARTED';
export const AJAX_REQUEST_FAILED = 'AJAX_REQUEST_FAILED';
export const AJAX_REQUEST_RESET = 'AJAX_REQUEST_RESET';
export const DICTIONARY_SELECTED = 'DICTIONARY_SELECTED';
export const ITEMS_CLASS_CREATED = 'ITEMS_CLASS_CREATED';
export const FETCH_ITEMS_STARTED = 'FETCH_ITEMS_STARTED';
export const FETCH_ITEMS_SUCCEED = 'FETCH_ITEMS_SUCCEED';
export const BACK_HOME = "BACK_HOME";
export const ADD_NEW_ITEM_REQUEST_SUCCEED = "ADD_NEW_ITEM_REQUEST_SUCCEED";
