/**
 * Created by alexanderbol on 09/01/2016.
 */
export const BACK_HOME_BUTTON_PRESSED = 'BACK_HOME_BUTTON_PRESSED';
export const EDIT_MODE_BUTTON_PRESSED = 'EDIT_MODE_BUTTON_PRESSED';
export const LEARN_MODE_BUTTON_PRESSED = 'LEARN_MODE_BUTTON_PRESSED';
export const BUTTON_SORTED_BY_PRESSED = 'BUTTON_SORTED_BY_PRESSED';
export const CONFIG_BUTTON_PRESSED = 'CONFIG_BUTTON_PRESSED';
export const BACK_TO_DICTIONARY_VIEW_PRESSED = 'BACK_TO_DICTIONARY_VIEW_PRESSED';

export const HOME_MENU_BUTTON_PRESSED = 'HOME_MENU_BUTTON_PRESSED';
export const MENU_ITEM_LOGOUT_PRESSED = 'MENU_ITEM_LOGOUT_PRESSED';

export const FETCH_SHARES_REQUEST_SUCCEED = 'FETCH_SHARES_REQUEST_SUCCEED';

export const FETCH_DICTIONARIES_REQUEST_SUCCEED = 'FETCH_DICTIONARIES_REQUEST_SUCCEED';
export const DICTIONARY_SELECTED = 'DICTIONARY_SELECTED';
export const DICTIONARY_UPDATED = 'DICTIONARY_UPDATED';
export const ADD_DICTIONARY_BUTTON_PRESSED = 'ADD_DICTIONARY_BUTTON_PRESSED';
export const NEW_DICTIONARY_SAVE_REQUEST_SUCCEED = 'NEW_DICTIONARY_SAVE_REQUEST_SUCCEED';
export const DELETE_DICTIONARY_BUTTON_PRESSED = 'DELETE_DICTIONARY_BUTTON_PRESSED';
export const DELETE_DICTIONARY_REQUEST_SUCCEED = 'DELETE_DICTIONARY_REQUEST_SUCCEED';
export const DELETE_SHARE_REQUEST_SUCCEED = 'DELETE_SHARE_REQUEST_SUCCEED';

export const FETCH_LANGUAGES_REQUEST_SUCCEES = 'FETCH_LANGUAGES_REQUEST_SUCCEES';

export const ITEMS_CLASS_CREATED = 'ITEMS_CLASS_CREATED';
export const FETCH_ITEMS_STARTED = 'FETCH_ITEMS_STARTED';

export const FETCH_ITEMS_SUCCEED = 'FETCH_ITEMS_SUCCEED';
export const LEFT_ITEM_CLICKED = "LEFT_ITEM_CLICKED";
export const RIGHT_ITEM_CLICKED = "RIGHT_ITEM_CLICKED";
export const ITEMS_MATCHED = 'ITEMS_MATCHED';
export const LEARN_ITEMS_REFRESHED = 'LEARN_ITEMS_REFRESHED';

export const AJAX_REQUEST_STARTED = 'AJAX_REQUEST_STARTED';
export const AJAX_REQUEST_FAILED = 'AJAX_REQUEST_FAILED';
export const AJAX_REQUEST_RESET = 'AJAX_REQUEST_RESET';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_IN_TO_PARSE = 'USER_LOGGED_IN_TO_PARSE';
export const USER_LOGIN_FOUND = 'USER_LOGIN_FOUND';
export const USER_LOGIN_NOT_FOUND = 'USER_LOGIN_NOT_FOUND';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGIN_CANCELLED = 'USER_LOGIN_CANCELLED';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_MISSING_PERMISSIONS = 'USER_LOGIN_MISSING_PERMISSIONS';

export const FETCH_USER_DATA_REQUEST_SUCCEED = 'FETCH_USER_DATA_REQUEST_SUCCEED';

/* Edit new dictionary */
export const TOGGLE_LANGUAGE1_PICKER_PRESSED = 'TOGGLE_LANGUAGE1_PICKER_PRESSED';
export const TOGGLE_LANGUAGE2_PICKER_PRESSED = 'TOGGLE_LANGUAGE2_PICKER_PRESSED';

/* Edit mode - browse and edit  list of items */
export const SELECT_ITEM_PRESSED = 'SELECT_ITEM_PRESSED';
export const EDIT_ITEM_BUTTON_PRESSED = 'EDIT_ITEM_BUTTON_PRESSED';
export const ADD_NEW_ITEM_REQUEST_SUCCEED = "ADD_NEW_ITEM_REQUEST_SUCCEED";
export const DELETE_ITEM_REQUEST_SUCCEED = 'DELETE_ITEM_REQUEST_SUCCEED';
export const ITEM_CHANGED = 'ITEM_CHANGED';
export const GO_WEB_BUTTON_PRESSED = 'GO_WEB_BUTTON_PRESSED';
