/**
 * Created by alexanderbol on 09/01/2016.
 */
export const BACK_HOME_BUTTON_PRESSED = 'BACK_HOME_BUTTON_PRESSED';
export const EDIT_MODE_BUTTON_PRESSED = 'EDIT_MODE_BUTTON_PRESSED';
export const LEARN_MODE_BUTTON_PRESSED = 'LEARN_MODE_BUTTON_PRESSED';
export const BUTTON_SORTED_BY_PRESSED = 'BUTTON_SORTED_BY_PRESSED';
export const CONFIG_BUTTON_PRESSED = 'CONFIG_BUTTON_PRESSED';
export const BACK_TO_DICTIONARY_VIEW_PRESSED = 'BACK_TO_DICTIONARY_VIEW_PRESSED';
export const LEFT_SEARCH_INPUT_GOT_FOCUS = 'LEFT_SEARCH_INPUT_GOT_FOCUS';
export const RIGHT_SEARCH_INPUT_GOT_FOCUS = 'RIGHT_SEARCH_INPUT_GOT_FOCUS';
export const LEFT_SEARCH_PATTERN_CHANGED = 'LEFT_SEARCH_PATTERN_CHANGED';
export const RIGHT_SEARCH_PATTERN_CHANGED = 'RIGHT_SEARCH_PATTERN_CHANGED';
export const LEFT_CLEAN_SEARCH_PATTERN_PRESSED = 'LEFT_CLEAN_SEARCH_PATTERN_PRESSED';
export const RIGHT_CLEAN_SEARCH_PATTERN_PRESSED = 'RIGHT_CLEAN_SEARCH_PATTERN_PRESSED';
export const SWITCH_LANGUAGE_PANELS_PRESSED = 'SWITCH_LANGUAGE_PANELS_PRESSED';

export const HOME_MENU_BUTTON_PRESSED = 'HOME_MENU_BUTTON_PRESSED';
export const MENU_ITEM_LOGOUT_PRESSED = 'MENU_ITEM_LOGOUT_PRESSED';

export const FETCH_SHARES_REQUEST_SUCCEED = 'FETCH_SHARES_REQUEST_SUCCEED';
export const SHARE_DICTIONARY_REQUEST_SUCCEED = 'SHARE_DICTIONARY_REQUEST_SUCCEED';

export const FETCH_DICTIONARIES_REQUEST_SUCCEED = 'FETCH_DICTIONARIES_REQUEST_SUCCEED';
export const DICTIONARY_SELECTED = 'DICTIONARY_SELECTED';
export const DICTIONARY_UPDATED = 'DICTIONARY_UPDATED';
export const ADD_NEW_DICTIONARY_BUTTON_PRESSED = 'ADD_NEW_DICTIONARY_BUTTON_PRESSED';
export const NEW_DICTIONARY_SAVE_REQUEST_SUCCEED = 'NEW_DICTIONARY_SAVE_REQUEST_SUCCEED';
export const DELETE_DICTIONARY_BUTTON_PRESSED = 'DELETE_DICTIONARY_BUTTON_PRESSED';
export const DELETE_DICTIONARY_REQUEST_SUCCEED = 'DELETE_DICTIONARY_REQUEST_SUCCEED';
export const DELETE_SHARE_REQUEST_SUCCEED = 'DELETE_SHARE_REQUEST_SUCCEED';

export const FETCH_LANGUAGES_REQUEST_SUCCEED = 'FETCH_LANGUAGES_REQUEST_SUCCEED';

export const ITEMS_CLASS_CREATED = 'ITEMS_CLASS_CREATED';
export const FETCH_ITEMS_STARTED = 'FETCH_ITEMS_STARTED';

export const FETCH_ITEMS_SUCCEED = 'FETCH_ITEMS_SUCCEED';
export const FETCH_ITEMS_PAGE_SUCCEED = 'FETCH_ITEMS_PAGE_SUCCEED';
export const LEFT_ITEM_CLICKED = "LEFT_ITEM_CLICKED";
export const RIGHT_ITEM_CLICKED = "RIGHT_ITEM_CLICKED";
export const ITEMS_MATCHED = 'ITEMS_MATCHED';
export const LEARN_ITEMS_REFRESHED = 'LEARN_ITEMS_REFRESHED';

export const AJAX_REQUEST_STARTED = 'AJAX_REQUEST_STARTED';
export const AJAX_REQUEST_FAILED = 'AJAX_REQUEST_FAILED';
export const AJAX_REQUEST_RESET = 'AJAX_REQUEST_RESET';

// export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_IN_TO_PARSE = 'USER_LOGGED_IN_TO_PARSE';
// export const USER_LOGIN_FOUND = 'USER_LOGIN_FOUND';
// export const USER_LOGIN_NOT_FOUND = 'USER_LOGIN_NOT_FOUND';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const FETCH_USER_DATA_REQUEST_SUCCEED = 'FETCH_USER_DATA_REQUEST_SUCCEED';

/* Edit mode - browse and edit  list of items */
export const SELECT_ITEM_PRESSED = 'SELECT_ITEM_PRESSED';
export const EDIT_ITEM_BUTTON_PRESSED = 'EDIT_ITEM_BUTTON_PRESSED';
export const FORCE_EDIT_ITEM_PRESSED = 'FORCE_EDIT_ITEM_PRESSED';
export const ADD_NEW_ITEM_REQUEST_SUCCEED = "ADD_NEW_ITEM_REQUEST_SUCCEED";
export const DELETE_ITEM_REQUEST_SUCCEED = 'DELETE_ITEM_REQUEST_SUCCEED';
export const ITEM_CHANGED = 'ITEM_CHANGED';
export const ITEM_CHANGE_DONE = 'ITEM_CHANGE_DONE';
export const GO_WEB_BUTTON_PRESSED = 'GO_WEB_BUTTON_PRESSED';

export const AUTO_TRANSLATE_SWITCH_TOGGLED = 'AUTO_TRANSLATE_SWITCH_TOGGLED';

export const TTS_LOCALES_REQUEST_SUCCEED = 'TTS_LOCALES_REQUEST_SUCCEED';